### ISSUE TITLE
TF_transformations as well as navigation_interface.msg not being scanned

### ISSUE THREAD

**Issue by MillionDlr01** [JACart2/ai-navigation#1]
First thing we need to do is make sure we can get tf_transformations installed correctly. I tried looking at some things on how to install it but nothing seemed useful so far... so finding a way to get that install is crucial to moving forward with nav. Also I think navigation_interface import is just messing up in vscode. Everything is probably fine there just thought i should mention it.

**Comment by spragunr** [comment]
You should be able to just:
`sudo apt install ros-humble-tf-transformations`

**Comment by MillionDlr01** [comment]
This has been resolved with the above comment
