### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by martinnester** [JACart2/ai-navigation#8]
- Probably start from existing ROS2 humble dockerfile
- Add additional dependencies from: https://github.com/JACart2/jacart2_documentation/blob/main/complete_setup_readme.md
**Issues:**
- Connecting to serial port from docker image???
- https://stackoverflow.com/a/24231872
- And other USB devices???
- Showing the GUI???
- https://www.howtogeek.com/devops/how-to-run-gui-applications-in-a-docker-container

**Comment by eospra** [comment]
add a flag to run with or without the usb link
